- name: Install Mariadb server
  apt: name=mariadb-server state=present

- name: Enable mariadb service
  service: name=mariadb enabled=yes state=started

- name: Install python3 mysql connector
  apt: name=python3-mysqldb state=present
