- name: Generate .env
  template:
    src: templates/.env.j2
    dest: "{{ laravel_app_path }}/.env"

- name: Add env variables
  lineinfile:
    path: "{{ laravel_app_path }}/.env"
    line: "{{ item }}"
    insertafter: EOF
  loop:
    - "APP_URL=192.168.68.17"
    - "DB_CONNECTION=mysql"
    - "DB_HOST={{ mysql_host }}"
    - "DB_PORT=3306"
    - "DB_DATABASE={{ mysql_database }}"
    - "DB_USERNAME={{ mysql_user }}"
    - "DB_PASSWORD={{ mysql_password }}"

- name: Generate application key
  command: "php artisan key:generate"
  args:
    chdir: "{{ laravel_app_path }}"
