- name: Apt update
  apt:
    update_cache: yes

- name: Install Laravel
  apt:
    name: "{{ item }}"

  loop:
    - git
    - curl
    - unzip
    - php{{ laravel_php_version }}
    - php{{ laravel_php_version }}-cli
    - php{{ laravel_php_version }}-mbstring
    - php{{ laravel_php_version }}-xml
    - php{{ laravel_php_version }}-curl
    - php{{ laravel_php_version }}-zip
    - php{{ laravel_php_version }}-fpm
    - php{{ laravel_php_version }}-mysql
    - composer

- name: Clone git Repository
  git:
    repo: "{{ repo_url }}"
    dest: "{{ laravel_app_path }}"
    version: "{{ branch }}"
  register: repo

- name: Update Laravel dependencies
  shell: "COMPOSER_ALLOW_SUPERUSER=1 bash -c 'composer install --no-dev'"
  args:
    chdir: "{{ laravel_app_path }}"
  when: repo.changed

- name: Check if .env exists
  stat:
    path: "{{ laravel_app_path }}/.env"
  register: env_file

- name: Generate .env
  ansible.builtin.import_tasks:
    file: playbooks/backend/generate_env_file.yml
  when: env_file.stat.exists == false

- name: "Cache the configuration"
  shell: "php artisan config:cache"
  args:
    chdir: "{{ laravel_app_path }}"
  when: repo.changed

- name: "Clear the view cache"
  shell: "php artisan view:clear"
  args:
    chdir: "{{ laravel_app_path }}"
  when: repo.changed

- name: "Run the migrations"
  shell: "php artisan migrate --force"
  args:
    chdir: "{{ laravel_app_path }}"
  when: repo.changed
