- name: Apt update
  apt:
    update_cache: yes

- name: Install dependencies
  apt:
    name: "{{item}}"
    state: present
  loop:
    - "nginx"
    - "unzip"
    - "git"
    - "curl"
    - "build-essential"
    - "python2"
  register: installed_dependencies

- name: Install nvm
  ansible.builtin.import_tasks:
    file: playbooks/frontend/nvm.yml
  when: installed_dependencies.changed

- name: Setup nginx
  ansible.builtin.import_tasks:
    file: playbooks/frontend/nginx.yml
  when: installed_dependencies.changed

- name: Clone repository
  git:
    repo: "{{ repo_url }}"
    dest: "{{ angular_app_path }}"
    version: "{{ branch }}"
  register: repo

- name: Build Angular app
  ansible.builtin.import_tasks:
    file: playbooks/frontend/build.yml
  when: repo.changed
